### PR TITLE
Switched pyautogui.screenshot() to mss module

### PR DESCRIPTION
**Pull request by calvindo95**
The pyautogui.screenshot() function is notoriously slow, using the mss module to screen grab is significantly faster.

### CODE REVIEW

**Comment by OzgunKB** [comment]
d3dshot?
https://pypi.org/project/d3dshot/

**Comment by drov0** [comment]
@calvindo95  Thanks a lot ! I will do a review soon !

@OzgunKB we can't use d3dshot because it's windows specific and the lib is cross platform. 

if performance is really increased from mss I'll look into it but I'm not a fan of having platform-specific calls as in increases the bug surface

**Comment by drov0** [comment]
@calvindo95 

The proposed changes fail to run on my computer: (ubuntu)

```
Traceback (most recent call last):
  File "simple_example.py", line 3, in <module>
    pos = imagesearch("./github.png")
  File "imagesearch.py", line 118, in imagesearch
    im = sct.grab()
TypeError: grab() missing 1 required positional argument: 'monitor'
```

looking at the mss doc, you need to pass a monitor object to the grab: https://python-mss.readthedocs.io/examples.html#a-screen-shot-to-grab-them-all 

Just add all the screens (aka the maximum resolution) to capture everything when doing a simple imagesearch.

Which platform are you using ? 

Also could you add mss to requirements.txt ?

**Comment by calvindo95** [comment]
@drov0 I fixed the monitor object and I'm using Ubuntu

**Comment by drov0** [comment]
@calvindo95 LGTM ! 

I did some tests with mss, and the performance gains is incredible ! The optimized search where you re-use the same grabbed region is almost not necessary anymore :) 

Thanks a lot for your contribution ! :)

**Comment by excitoon** [comment]
@calvindo95 you've broken Retina here, see #53

**Pull request merged**
